# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-12 09:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fb', '0006_auto_20171212_1320'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dailyrecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateField(auto_now=True, verbose_name='日期')),
                ('topic', models.CharField(max_length=255, verbose_name='教學單元')),
                ('studentnum', models.CharField(max_length=255, verbose_name='學生人數')),
                ('attend', models.CharField(max_length=255, verbose_name='出席人數')),
                ('absence', models.CharField(max_length=255, verbose_name='缺席人數')),
                ('title', models.CharField(max_length=255, verbose_name='教學日誌標題')),
                ('event', models.CharField(max_length=2550, verbose_name='偶發事件處理事項')),
                ('content', models.TextField(max_length=2550, verbose_name='教學內容')),
                ('introspective', models.TextField(max_length=2550, verbose_name='教學省思')),
                ('image', models.ImageField(blank=True, upload_to='dailyrecord/', verbose_name='教學日誌圖片')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dailyrecord', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
