# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-12 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb', '0008_announcement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='datetime',
            field=models.CharField(max_length=255, verbose_name='公告時間'),
        ),
    ]
