# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-11 06:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='jktree',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=300)),
                ('time', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='mmready',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=300)),
                ('time', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='Mombaby',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=300)),
                ('time', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
