# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-11 07:46
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Studentinformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='家長連絡登入帳戶')),
                ('name', models.CharField(max_length=255, verbose_name='家長姓名')),
                ('childName', models.CharField(max_length=255, verbose_name='小朋友姓名')),
                ('phone', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(9)], verbose_name='家長聯絡電話(手機)')),
                ('useraddress', models.CharField(blank=True, max_length=255, verbose_name='家庭住址')),
                ('usercontact', models.CharField(blank=True, max_length=255, verbose_name='家長與孩童關係')),
            ],
        ),
        migrations.AlterField(
            model_name='schoolclass',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schoolclass', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentinformation',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studentInfor', to='fb.Schoolclass'),
        ),
    ]
