# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-11 14:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fb', '0002_auto_20171211_1546'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ebook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='標題')),
                ('image', models.ImageField(upload_to='ebookcovers/', verbose_name='電子書封面')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ebook', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
