# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-11 14:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fb', '0003_ebook'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ebook_detail',
            fields=[
                ('image', models.ImageField(blank=True, upload_to='profiles/', verbose_name='電子書圖片')),
                ('sortbynumber', models.AutoField(primary_key=True, serialize=False)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ebookdetail', to='fb.Ebook')),
            ],
        ),
    ]
