# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-12 05:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fb', '0004_ebook_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contactbook2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='聯絡簿標題')),
                ('content', models.CharField(max_length=255, verbose_name='細項內容')),
                ('honor', models.CharField(max_length=255, verbose_name='表彰名單')),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('imagecontact', models.ImageField(blank=True, upload_to='contactbook/')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactbook2', to='fb.Schoolclass')),
            ],
        ),
        migrations.CreateModel(
            name='Contacturl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255, verbose_name='傳送url')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacturl', to='fb.Contactbook2')),
            ],
        ),
    ]
