# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-12 15:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fb', '0007_dailyrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateField(verbose_name='選擇日期')),
                ('title', models.CharField(max_length=255, verbose_name='公告標題')),
                ('content', models.CharField(max_length=2550, verbose_name='公告內容')),
                ('file', models.FileField(blank=True, upload_to='announce/', verbose_name='上傳檔案')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announce', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
